### PR TITLE
Temperature at place

### PR DESCRIPTION
**Pull request by Laughing-Boy**
Fixes issue #97 
image
Etherpad link : http://dream.susi.ai/p/temperature_at_place

### CODE REVIEW

**Comment by AliAyub007** [comment]
@jyoth1raditya  There is already this skill in weather.txt  kindly see this 
https://github.com/fossasia/susi_skill_data/blob/master/models/general/knowledge/en/weather_information.txt

**Review by rishiraj824 — APPROVED** [review]

**Comment by hpdang** [comment]
@AliAyub007 the current skill doesn't give the correct answer though, could you check? Below was what I got 
screen shot 2017-06-09 at 3 33 34 pm

**Comment by AliAyub007** [comment]
@hpdang  yes sure and i got the problem why is it happening so will send the updated version for this.

**Review by dynamitechetan — APPROVED** [review]

**Comment by hpdang** [comment]
im closing this issue, please work on https://github.com/fossasia/susi_skill_data/issues/122

**Pull request closed without merging**
