### PR TITLE
added skill to tell cats fact

### PR DESCRIPTION
**Pull request by saurabhjn76**
Fixes issue #147, progress on #88 

Changes: added skill to give fun facts about cat 

Screenshots for the change: 
image
 Etherpad link to test : [http://dream.susi.ai/p/cat](http://dream.susi.ai/p/cat)

### CODE REVIEW

**Comment by saurabhjn76** [comment]
@dynamitechetan @DravitLochan @madhavrathi @jyoth1raditya please review

**Review by madhavrathi — APPROVED** [review]
LGTM

**Review by dynamitechetan — APPROVED** [review]

**Review by isuruAb — APPROVED** [review]

**Comment by hpdang** [comment]
thanks @saurabhjn76. Top skills could also be those very high number of reviews from users. I saw those with over a few hundreds to 1,000 reviews. 

screen shot 2017-06-17 at 8 15 12 pm

**Comment by saurabhjn76** [comment]
@hpdang I would look forward to add the top skills in Susi. :+1:

**Pull request merged**
