### PR TITLE
Create ferengi_rules_of_acquisition.txt

### PR DESCRIPTION
**Pull request by Laughing-Boy**
Fixes issue #156, Susi responds with appropriate rules of acquisition.

Screenshots for the change: 
image

Etharpad link : http://dream.susi.ai/p/ferengi

### CODE REVIEW

**Comment by Laughing-Boy** [comment]
@hpdang @DravitLochan @saurabhjn76 @dynamitechetan @isuruAb @rishiraj824 @madhavrathi @uday96
Please review, and suggest necessary changes.

**Review by madhavrathi — APPROVED** [review]

**Review by saurabhjn76 — APPROVED** [review]

**Review by uday96 — APPROVED** [review]

**Review by mariobehling — CHANGES_REQUESTED** [review]
You are creating dependencies to your personal repository. Have you done this elsewhere as well? This is not good. The service cannot rely on personal repositories of students, that might easily change. Imagine if lots of students do this. Someone will change their repo at one point. We should depend on services that are continuously there already for some time and include data in our repo itself.

Please check how data can be extracted from this wiki site. 

http://memory-beta.wikia.com/wiki/Ferengi_Rules_of_Acquisition

**Review by madhavrathi — CHANGES_REQUESTED** [review]
Please find a way around, as you should not use your private repository for skill development tasks, as in future if the repository get's deleted, then there will be issues.

Thanks

**Comment by Laughing-Boy** [comment]
@mariobehling, As per ur sugestion I explored wikia api. Site makers of startrek have decided to not to not allow commercial use. http://memory-alpha.wikia.com/api/v1/Articles/Details/?ids=27 .
I have already searched for api related to star trek. There weren't any.
So, Can we use fossasia's or your git to  host the json file.

**Comment by mariobehling** [comment]
> Site makers of startrek have decided to not to not allow commercial use.

This is not a problem for us at the moment and operate more like a search engine. Whatever is published on the Internet would be possible therefore. Please proceed with using the wikia-site.

**Comment by Laughing-Boy** [comment]
@mariobehling , Thanks for reply. Can you elaborate the process.

**Comment by mariobehling** [comment]
Do you want me to solve this issue or will you?
https://www.youtube.com/watch?v=7U__K8yy1iY

**Comment by hpdang** [comment]
@jyoth1raditya please take care of reviewers' comments. It has been a while already.

**Comment by dynamitechetan** [comment]
http://ferengi.surge.sh/rules.json 
can we use this?
@jyoth1raditya @mariobehling

**Review by dynamitechetan — APPROVED** [review]

**Pull request merged**
