### PR TITLE
Added Insult.txt to generate insults [Alexa Skill] [Milestone 7]

### PR DESCRIPTION
**Pull request by dynamitechetan**
Fixes issue #164 
Etherpad Url: http://dream.susi.ai/p/insult
Similar to: https://www.amazon.com/gp/product/B06W5GWD3R?ref=skillrw_dsk_tmss_gw_3
Screenshots for the change: 
image

### CODE REVIEW

**Comment by dynamitechetan** [comment]
@jyoth1raditya @madhavrathi @isuruAb @saurabhjn76  please review

**Comment by hpdang** [comment]
@dynamitechetan ask your friends to review plz

**Review by hpdang — CHANGES_REQUESTED** [review]
@dynamitechetan Did you check the result from Amazon? The insult that susi generated is not funny and difficult to understand for a non-native English speaker. Any other source of answers? Can we use this skill to ask for: give me a bad word, say a bad word etc, extend it further cover: curse, swearing, swear word, profanity, foul language etc.

**Comment by dynamitechetan** [comment]
@hpdang I found this API only. Also, some other co-developer was asked not to use their own source of data for Skills.

**Comment by hpdang** [comment]
@dynamitechetan there's also the second part in my previous comment, can we extend this further, cover: give me a bad word, say a bad word etc, curse, swearing, swear word, profanity, foul language etc.

**Comment by dynamitechetan** [comment]
@hpdang giving bad words, foul language usage etc. can be hard-coded. Can we have a different file for those words?

**Comment by hpdang** [comment]
@dynamitechetan the idea is that a skill can store more than just one answer. I will merge this PR if there are approved reviews from your peer, but please create another issue to extend this skill the way I described earlier. Thanks

**Review by saurabhjn76 — APPROVED** [review]

**Review by madhavrathi — APPROVED** [review]

**Review by DravitLochan — APPROVED** [review]

**Review by Laughing-Boy — APPROVED** [review]

**Pull request merged**
