### PR TITLE
returns different images on different queries

### PR DESCRIPTION
**Pull request by DravitLochan**
Fixes issue #81 

Changes: added a skill file for images

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
@DravitLochan please add the description with the dream URL and a screenshot of the output.

**Comment by DravitLochan** [comment]
[dream](dream.susi.ai/p/images)
In this dream, 3 aspects are covered. 
1. random images (link to any random image)
2. images of a particular search query (gives out a link to an image based on search item)
3. latest images (gives out 10 links to images)

**Comment by Manveer695** [comment]
@DravitLochan Your dream url is incorrect. For reviewers, the correct link is [dream url](http://dream.susi.ai/p/images).

Also I am getting no result for the dream images:
capture

**Comment by hpdang** [comment]
guys, if you do not make changes according to your colleague's comments/reviews, I will close the PR/issue. There are many other more relevant skills that we should work on

**Comment by DravitLochan** [comment]
I am really sorry but I must have missed his last comment. I apologise. @hpdang ma'am should I open a new pr for the same skill?

**Pull request closed without merging**
