### PR TITLE
fixes #37, updated time.txt

### LINKED ISSUE #37: Incorrect results for time query
**Actual Behaviour**

Currently, for query ' current time in <country> ' , answer shown are not correct.

**Expected Behaviour**

It should show time in respective country's time zone.

**Screenshots of the issue**

susi_bad

### PR DESCRIPTION
**Pull request by saurabhjn76**
Fixes issue #37 

Changes: updated `time.txt` in `models/general/knowledge/en/`

Screenshots for the change: 
image
Etherpad link for testing -[http://dream.susi.ai/p/time1](http://dream.susi.ai/p/time1)
Service used - [https://api.wolframalpha.com/](https://api.wolframalpha.com/)

### CODE REVIEW

**Review by dynamitechetan — APPROVED** [review]

**Review by DravitLochan — APPROVED** [review]

**Review by Laughing-Boy — APPROVED** [review]

**Comment by mariobehling** [comment]
Please provide an Etherpad dream to test this skill.

Follow best practices in all projects!

**Comment by saurabhjn76** [comment]
Etherpad link for testing -[http://dream.susi.ai/p/time1](http://dream.susi.ai/p/time1)

**Review by AliAyub007 — APPROVED** [review]

**Review by hpdang — CHANGES_REQUESTED** [review]
we need more questions that lead to the same answers.  1) time in * now or time in * 2) what is the time in * 3) Can you/could you tell me/Tell me + your questions about time here etc.

**Comment by saurabhjn76** [comment]
@hpdang added few questions please review

**Comment by hpdang** [comment]
@saurabhjn76 the previous API doesn't work? Why do we need to use wolframalpha again? according what I see, if I ask exactly "current time in Berlin" susi will give the correct answer but if I changed the question, she is no longer able to answer 

screen shot 2017-06-11 at 11 22 46 am

**Comment by saurabhjn76** [comment]
image
@hpdang yes previous API is not showing correct results, I will search why susi is not able to answer the query when the question is changed and will correct it. Thanks

**Comment by hpdang** [comment]
@saurabhjn76 the result that I gave you (screenshot) is from the previous API

**Comment by saurabhjn76** [comment]
@hpdang I checked it again and found that only for some places like Berlin the time was correct. But for India and other countries, it was showing incorrect results.
image
Also for query "time in Berlin" it is matching in [English-standaloneaiml2susi.txt](https://raw.githubusercontent.com/fossasia/susi_skill_data/master/models/general/smalltalk/en/English-Standalone-aiml2susi.txt)
image

**Comment by saurabhjn76** [comment]
@hpdang the updated PR is working fine for above issues.

**Review by isuruAb — APPROVED** [review]
Awesome now it works fine

**Pull request merged**
