### PR TITLE
Related to #48: Added skill to get nutritional facts for things Belongs to knowledge topic

### PR DESCRIPTION
**Pull request by AliAyub007**
Fixes issue #48 : Added skills to tell nutritional facts like proteins, fat, carbohydrates in food stuff.

### CODE REVIEW

**Review by Laughing-Boy — APPROVED** [review]

**Review by saurabhjn76 — APPROVED** [review]

**Comment by mariobehling** [comment]
Which issue? Where? Link? Please provide an Etherpad dream to test this skill.

Follow best practices in all projects!

Please do follow best practices. Read again the guidelines to understand the best practices of FOSSASIA.

**Comment by AliAyub007** [comment]
Issue #48 
Etherpad link: http://dream.susi.ai/p/nutritionalfacts

**Comment by hpdang** [comment]
@AliAyub007 can you plz make separate PRs for your commits, that wll make things easier for reviewer

**Comment by AliAyub007** [comment]
@hpdang Sorry for this I made a mistake for this at that time so that's why there is this issue only for this PR.

**Pull request closed without merging**
