### PR TITLE
Added remembering skill

### PR DESCRIPTION
**Pull request by Manveer695**
Fixes issue #181 i.e. Susi does not remember what the user told it to.

Etherpad Link: http://dream.susi.ai/p/remember

Screenshots for the change: 
meetingremember
answerremembermeeting
remember wallet

### CODE REVIEW

**Comment by Manveer695** [comment]
@AliAyub007 @dynamitechetan @DravitLochan @betterclever Please review it guys! Thanks.

**Review by DravitLochan — CHANGES_REQUESTED** [review]
1. add more questions like remember my * is *
2. add example to your skill

**Review by rishiraj824 — CHANGES_REQUESTED** [review]
@Manveer695 This is really nice! Though we can add lots of queries, for this other than remember, example remind me *, help me remember * , Please remind me to *

**Review by dynamitechetan — APPROVED** [review]

**Review by AliAyub007 — APPROVED** [review]

**Review by uday96 — COMMENTED** [review]
Add !example to the skill

**Comment by Manveer695** [comment]
@uday96 I have already added it.

**Review by DravitLochan — APPROVED** [review]

**Review by saurabhjn76 — APPROVED** [review]

**Review by Orbiter — APPROVED** [review]
looks good!

**Pull request merged**
