### PR TITLE
added a skill to play lizard spoke game

### PR DESCRIPTION
**Pull request by saurabhjn76**
Fixes issue #149, progress for #88 

Changes: added a skill to Play Rock, Paper, Scissors, Lizard, Spock game

Screenshots for the change: 
image
Link for testing [http://dream.susi.ai/p/game](http://dream.susi.ai/p/game)

### CODE REVIEW

**Review by DravitLochan — APPROVED** [review]

**Comment by saurabhjn76** [comment]
@dynamitechetan @madhavrathi @jyoth1raditya @AliAyub007 please review

**Review by AliAyub007 — APPROVED** [review]
Good One 👍

**Review by madhavrathi — APPROVED** [review]
Very innovative 👍

**Comment by hpdang** [comment]
good fun, btw @saurabhjn76 how Alexa performs this skill? Did you see? similar output like susi?

**Comment by saurabhjn76** [comment]
@hpdang, yes I checked Alexa for this skill, the difference is, here the user has to reveal his variable first, but Alexa speaks up at same time also Alexa explain how one won or lost just like susi, but it also keeps track of the wins and tells who racked up the most wins in several rounds.

**Review by isuruAb — APPROVED** [review]

**Pull request merged**
