### PR TITLE
Added extra question to country information skill

### PR DESCRIPTION
**Pull request by AliAyub007**
Partially fixes issue #119 

Changes: 
Added more questions to country information skill

### CODE REVIEW

**Comment by Manveer695** [comment]
@AliAyub007 Please make the travis check pass. I think an empty .travis.yml file would make it work, but @chashmeetsingh can guide you better.

**Comment by hpdang** [comment]
@AliAyub007 please take care of reviewer's comment

**Comment by AliAyub007** [comment]
@hpdang As discussed there is no need of CI build in this repository and it will be removed so I didn't add it.

**Comment by hpdang** [comment]
@AliAyub007 please ask for reviews from your fellow developers

**Review by rishiraj824 — APPROVED** [review]

**Review by saurabhjn76 — APPROVED** [review]

**Review by DravitLochan — COMMENTED** [review]
Nice work! Please also provide link to etherpad. 
Thanks.

**Review by Manveer695 — APPROVED** [review]

**Pull request merged**
