### PR TITLE
Added more languages

### LINKED ISSUE #337: Add more languages in the groups
**Actual Behaviour**

A lot of languages are missing in the groups.

**Expected Behaviour**

Add more languages.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AnupKumarPanwar**
Fixes #337 

Changes: 
Added more directories corresponding to the languages in the groups.

Screenshots for the change: 
NA

### CODE REVIEW

**Review by hkedia321 — COMMENTED** [review]
@AnupKumarPanwar I think that the languages folders were not there because there were no skills in that language for that category. Can you please explain why do we need to make empty folders for these languages? Thanks!

**Comment by AnupKumarPanwar** [comment]
@hkedia321 No that's not right there were already many empty folders for the languages in the skill categories. In fact, most of the folders were empty only some English skills were there. Also, some popular languages were missing like Chinese. So I added a folder for them as well.

**Comment by AnupKumarPanwar** [comment]
@akshatnitd @anshumanv @mariobehling  Please review. Reference has been taken from https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by AnupKumarPanwar** [comment]
@dynamitechetan @saurabhjn76 @isuruAb Please review.

**Review by dynamitechetan — APPROVED** [review]

**Comment by dynamitechetan** [comment]
Adding language folders in Skill data repo is the only way for the server to add new languages.

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
