### PR TITLE
Added Examples for Small talk skills

### PR DESCRIPTION
**Pull request by Laughing-Boy**
Fixes issue #208, Added various examples to skills in small talk.

### CODE REVIEW

**Comment by Laughing-Boy** [comment]
@dynamitechetan @saurabhjn76 @madhavrathi @rishiraj824 Please review

**Review by madhavrathi — APPROVED** [review]

**Review by Manveer695 — APPROVED** [review]

**Review by AliAyub007 — APPROVED** [review]

**Review by rishiraj824 — COMMENTED** [review]
@jyoth1raditya This is good but we can add more questions in small talk for example,
- What are you doing? 
- What's up? 
which are otherwise fetched as RSS responses

**Review by dynamitechetan — APPROVED** [review]

**Review by saurabhjn76 — APPROVED** [review]

**Review by mariobehling — CHANGES_REQUESTED** [review]
You example do not make sense. This skill is not a small talk skill as expected, but a number of points are insulting.

Syntax is missing on a lot of sentences, e.g. no full stop.

An example will be used to answer the question to Susi "What skills do you have?". Then SUSI can reply "You are bad" if I look at your examples. Does not really make sense they way you are putting up the skill here.

**Comment by mariobehling** [comment]
I am merging this as work in progress. Thank you.

**Pull request merged**
