### PR TITLE
Added rick_and_morty.txt to generate fun quotes

### PR DESCRIPTION
**Pull request by Laughing-Boy**
Fixes issue #163 , Skill successfully generates rick and morty quotes.

Screenshots for the change: 
image
image

Etharpad Link : http://dream.susi.ai/p/rickandmorty
The api I used, works as host for telegram app. So, this is reliable.
Blog explaining the api : https://tpei.blog/2016/12/05/randomquotes/
Telegram bot : http://telegram.me/RickAndMortyQuoterBot

### CODE REVIEW

**Comment by Laughing-Boy** [comment]
@DravitLochan @uday96 @madhavrathi @saurabhjn76 , Please review

**Comment by DravitLochan** [comment]
Please provide etherpad link.

**Comment by Laughing-Boy** [comment]
@madhavrathi @saurabhjn76 @uday96 
Please review, I know what happened last time. 
Things happen, we have to learn and move on. 😄

**Comment by Laughing-Boy** [comment]
@DravitLochan @isuruAb @dynamitechetan , Please review

**Review by isuruAb — APPROVED** [review]
LGTM 👍

**Comment by hpdang** [comment]
@jyoth1raditya: could you try to focus on issues of the correct milestone before come up with some random skills. It is not wrong what you did, the more skills we have the better. However can you prioritize and do more practical skills first? More practical means more people likely will ask for when they test susi.

**Review by madhavrathi — APPROVED** [review]

**Review by Manveer695 — APPROVED** [review]

**Review by rishiraj824 — APPROVED** [review]

**Review by uday96 — APPROVED** [review]

**Comment by Laughing-Boy** [comment]
@hpdang, I will definitely follow the milestones and will proceed with issues in it. Thanks for Input. :+1:
This PR is ready to be merged.

**Pull request merged**
