### PR TITLE
first step of live cricket match details

### PR DESCRIPTION
**Pull request by DravitLochan**
Changes: Added a skill which returns latest ongoing live match details
Does not displays all the details, but good for the first step!

### CODE REVIEW

**Review by Laughing-Boy — APPROVED** [review]

**Comment by AliAyub007** [comment]
@DravitLochan Kindly provide Etherpad link for this skill.

**Comment by DravitLochan** [comment]
http://dream.susi.ai/p/cricket

**Comment by Manveer695** [comment]
@DravitLochan When I tried it, I got this:
cricketskillissue

**Comment by DravitLochan** [comment]
@Manveer695 Please use [this](chat.susi.ai) link to test the skill.

**Comment by AliAyub007** [comment]
@DravitLochan  It's working but not getting score on id and at first it took time cause when I requested api app got active on heroku first and it took time. As heroku sleeps after 30 minutes of inactivity so in this api code just ping heroku app url after 20-30 minutes so that it can stay active.

**Comment by DravitLochan** [comment]
Ya sure! I am working on the feature to display the score when user provides an id. I must have forgot to remove that message from the skill. Will try to edit the code as well. Thanks

**Comment by dynamitechetan** [comment]
@AliAyub007 I hosted the API on heroku because I didn't found any other way to deploy python for free. Do we have any other options?

**Comment by AliAyub007** [comment]
@dynamitechetan  Actually heroku is a good option for free hosting but in it's free mode there is this issue but if you can add a function to ping your heroku app url on regular interval basis this issue will get solved. Still I will search for some other better options if I find something better I will share it.

**Review by Manveer695 — APPROVED** [review]

**Comment by hpdang** [comment]
@DravitLochan i don't see any change on this PR since 7 days ago, I am closing this PR and issue

**Comment by DravitLochan** [comment]
I was told by jyoth1raditya yesterday only that he has made the changes and
hence I need worry about it. He was waiting for this this to merge.

**Pull request closed without merging**
