### PR TITLE
Create when.txt

### PR DESCRIPTION
**Pull request by Laughing-Boy**
Fixes issue #57, Any query with `when` in it

screenshot 2017-05-25 10 03 42
screenshot 2017-05-25 10 03 34

Here is link to etherpad for testing : http://dream.susi.ai/p/when

### CODE REVIEW

**Review by chashmeetsingh — APPROVED** [review]

**Review by dynamitechetan — APPROVED** [review]

**Review by DravitLochan — APPROVED** [review]

**Review by chashmeetsingh — APPROVED** [review]

**Comment by chashmeetsingh** [comment]
@jyoth1raditya could we add why did * happen as well?

**Comment by mariobehling** [comment]
Which issue? Where? Link? Please provide an Etherpad dream to test this skill.

Follow best practices in all projects!

Please do follow best practices. Read again the guidelines to understand the best practices of FOSSASIA.

**Comment by Laughing-Boy** [comment]
@mariobehling, Updated the PR according to best practices

**Comment by hpdang** [comment]
guys, i wonder why do we always use the API from Wolframalpha? aren't there more options? It is not good to depend only on one data source

**Pull request merged**
