### PR TITLE
Added more questions to latest_phone.txt

### PR DESCRIPTION
**Pull request by AliAyub007**
Partially Fixes issue #119 

Etherpad Link: http://dream.susi.ai/p/phone

Changes: Added more questions to latest_phone.txt

### CODE REVIEW

**Review by madhavrathi — APPROVED** [review]
Please add !example query as well.
Thanks

**Review by rishiraj824 — APPROVED** [review]

**Review by Manveer695 — APPROVED** [review]

**Comment by mariobehling** [comment]
Add more questions please e.g. "What is the latest * phone", "What is the latest model of *" etc.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by AliAyub007** [comment]
I will commit this using new format soon.

**Comment by mariobehling** [comment]
When?

**Comment by AliAyub007** [comment]
@mariobehling Done.

**Review by saurabhjn76 — CHANGES_REQUESTED** [review]
Please write the skill name as Latest Phone instead of file name.

**Review by saurabhjn76 — APPROVED** [review]

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
