### PR TITLE
Add images to smalltalk skills

### PR DESCRIPTION
**Pull request by rishiraj824**
Fixes issue #242 

Changes: 
- Added images to all skills in small talk.

@dynamitechetan @saurabhjn76 @DravitLochan @uday96 @madhavrathi @AliAyub007  Please review.

### CODE REVIEW

**Review by saurabhjn76 — COMMENTED** [review]
@rishiraj824 great work, but I think we should upload the images in this repository itself.  What are your views?

**Review by DravitLochan — CHANGES_REQUESTED** [review]
Add images to this repo only

**Comment by Manveer695** [comment]
@rishiraj824 Also resolve the conflicts.

**Comment by rishiraj824** [comment]
@Manveer695 @DravitLochan Sure will add images to the repository and resolve conflicts.

**Review by mariobehling — CHANGES_REQUESTED** [review]
Some images are unrelated to the question. 

Images need to be stored in the repository.

**Comment by rishiraj824** [comment]
@mariobehling Please let me know if any changes to the images are to be made. I'll change them. Thanks!

**Comment by mariobehling** [comment]
Thank you.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
