### PR TITLE
Added food related queries and restaurant search

### PR DESCRIPTION
**Pull request by AliAyub007**
Partially Fixes issue #184  (WIP)

Etherpad Link: http://dream.susi.ai/p/food

Changes:
Added restaurant search and food suggestion it need more work I will send commits after completing it and will wind it up till tomorrow.

Screenshot:

screen shot 2017-07-02 at 6 35 23 pm

### CODE REVIEW

**Comment by AliAyub007** [comment]
@hpdang currently susi is not that much capable to get location. I tried getting location with IP I succeeded but as it runs on server it always give location where server is running so right now we have to get it done by getting city name from user and as soon as susi is capable enough we can implement that also.

**Comment by AliAyub007** [comment]
@Orbiter when we call a query like with ` sign as in tutorial it gives response. but if query returns table type data then calling other query like this doesn't work. Can you please guide me with this.
here is the dream http://dream.susi.ai/p/test2

and secondly can we use values stored in variables like >_variable in same message? like I used google place api here and for it I need latitude and longitude so I called another api to get these using `call` but query is not using lat and lng values store in current message else values are from second last msg.

**Comment by Orbiter** [comment]
I don't understand, everything that could be read from a variable that has been stored in the same message could be constructed from the origin where the other variable would have been assigned.

Please make an example how you would like to use that proposal.

**Comment by AliAyub007** [comment]
@Orbiter I have made this dream http://dream.susi.ai/p/test3
In this dream I am using google places API which takes latitude and longitude values as a parameter. when I send this message ->  restaurant in Islamabad? 

It calls latitude and longitude passing city name and store values in lat and lng variables 

then in same call I call places which is a google place api call and which takes latitude and longitude as parameter.

it looks like this 

restaurant in *
^`latitude $1$`^>_lat ^`longitude $1$`^>_lng `places` 

` sign will turn into format so don't think I haven't used it correctly I have used ` this correctly in dream.

But when I do this api url in places take values of lat and lng from second last message not from this current message. So in order to get restaurant for the place user have asked for we have to send the most recent values of variables i.e lat and png so that we can show correct results. 

In current dream if I call this 3 times this will happen.

restaurant in rawalpindi? -> it doesn't give restaurant. 

restaurant in lahore? -> it gives restaurant in rawalpindi

restaurant in karachi -> it gives restaurant in Lahore

**Review by mariobehling — CHANGES_REQUESTED** [review]
Add examples as outlined here: https://github.com/fossasia/susi_skill_data/blob/master/README_susi_skill_language_tutorial.md#adding-example-to-a-skill

**Comment by Orbiter** [comment]
you don't need to store coordinates in variables to make it usable in another intent, just pass it as a parameter!

**Comment by AliAyub007** [comment]
@Orbiter Sir I can't because when someone asks for restaurant first latitude and longitude of that place are found using nested query and then it calls another nested query which gives restaurant and last nested query uses that latitude and longitude to give places.

**Comment by Orbiter** [comment]
Ok, just return last,lon as one string from geocoding and then call the geocoding intent as backquoted reflection call.

**Comment by AliAyub007** [comment]
@Orbiter  There is something wrong with this dream that I made when I dreamed it server stopped working can you kindly have a look into this? 
http://dream.susi.ai/p/testfood

**Comment by mariobehling** [comment]
@AliAyub007 What is the status of this PR?

Please follow the latest format including
screenshot from 2017-08-03 08-01-25

**Comment by AliAyub007** [comment]
@mariobehling There was some issue and still we couldn't get latitude and longitude in same intent by SUSI. I will get back to this PR soon. I will start working on it again If I can find a way for it.

**Comment by mariobehling** [comment]
@AliAyub007 You cannot keep a PR open for a month. There is no logic to this.

**Comment by AliAyub007** [comment]
@mariobehling Sorry to keep it open for so long. Actually, SUSI couldn't do this yet so that is the reason. I am closing this for now as soon as we can get this done I will open it and complete it.

**Pull request closed without merging**
