### PR TITLE
Added skill for searching locally [Yahoo Query Language]

### PR DESCRIPTION
**Pull request by dynamitechetan**
Fixes issue #216 
Ehterpad URL: http://dream.susi.ai/p/chetan

image

### CODE REVIEW

**Review by madhavrathi — APPROVED** [review]

**Review by saurabhjn76 — APPROVED** [review]

**Review by rishiraj824 — APPROVED** [review]

**Review by Laughing-Boy — APPROVED** [review]

**Review by Manveer695 — APPROVED** [review]
Good one!

**Comment by mariobehling** [comment]
Example bang is missing. Every skills needs an example. Yahoo Query language offers a pipe for all kinds of data. Creating the skill with the name "yahoo query language" is therefore not suitable.

**Comment by mariobehling** [comment]
Is it possible to display these results on a map and match it with a location?

**Comment by dynamitechetan** [comment]
there are many results, so it would be a little difficult to plot them on a map. We also do not know which one is accurate or close to the user location.

**Comment by dynamitechetan** [comment]
@mariobehling  I've already added an example. See line number 2.
```!example: find sushi in miami ```

**Pull request merged**
