### PR TITLE
Updated messenger bots skill

### PR DESCRIPTION
**Pull request by Manveer695**
[Partly Fixes issue] #255 i.e. updated skill for messenger bots.

Etherpad Link: http://dream.susi.ai/p/getstarted

### CODE REVIEW

**Comment by Manveer695** [comment]
Please do not merge this Pull request. I may need to update it.

**Review by mariobehling — CHANGES_REQUESTED** [review]
This is incomplete and not following the standard.

**Comment by mariobehling** [comment]
Why is this skill called "Share skill"? Please create names that are relevant and don't overlap with actual sharing skills.

**Comment by Manveer695** [comment]
@mariobehling Changed the PR name sir to avoid confusions. In this PR, I have just added an intent to the original skill file. The original skill file has all the properties of name, author and other required properties. Thank you.

**Comment by mariobehling** [comment]
Follow format of skills and write SUSI.AI as usual. Add sufficient abilities to skill. This skill is too basic. Honestly, I would be expecting more from you in the third term.

**Comment by Manveer695** [comment]
@mariobehling I was observing other bots like SIRI. As mentioned earlier I will keep on updating this PR. I have updated it with some more skills. To be clear, some of the skills will have buttons along with the reply message in the messenger bots like this:
urgent1

Like SIRI, we can show some suggestions helping the user with fuzzy queries. Something like this:
urgent2

Thank you for your feedback. I will try my best to meet your expectations. :)

**Comment by mariobehling** [comment]
Follow the standard skill format!

**Comment by Manveer695** [comment]
@mariobehling Sir in this PR, I have just added some intents to the original skill file. The original skill file has all the properties of name, author, and other required properties. Thank you, sir.

**Comment by mariobehling** [comment]
Thanks.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
