### PR TITLE
Added skill to tell latest exchange rate for a currency

### PR DESCRIPTION
**Pull request by Manveer695**
Fixes issue #109 

Changes: 
A skill added to tell the latest exchange rates of a currency equivalent to 1 bitcoin.

Screenshots for the change: 
bitcoin

Susi dream link: 
http://dream.susi.ai/p/currencytobitcoin

### CODE REVIEW

**Comment by hpdang** [comment]
hi @Manveer695, this skill doesn't make sense to me. An exchange rate must involve 2 currencies. What can the number tell us? That is the exchange rate of any currency against what? the currency of the user based on his/her location?

**Comment by Manveer695** [comment]
Hi, good morning @hpdang . Actually, it tells us that how much denomination of a currency is equivalent to 1 BTC i.e. bitcoin. For Indian rupee(as it can be seen from the above figure), it is telling us that 179250.42 Indian rupee is equivalent to 1 bitcoin. 
I need to make the description of the skill more informative. I will immediately resolve that. Thank you for pointing it out.

**Comment by hpdang** [comment]
good @Manveer695, before we merge, could you add more possible questions that lead to the same answers. for example: 1) convert bitcoin/btc to usd/ us dollar/ us dollars, 2) bitcoin to usd/ us dollar/ us dollars 3) if we add 'tell me' 'can you tell me' 'could you tell me' 'do you know' in the beginning of your define questions here in this skill, make sure it also gives the answer. 4) And if the currency is not defined in your skill, then what will be the answer

**Comment by Manveer695** [comment]
@hpdang Tried my best to cover all the possible cases, hence made a new commit. Also, if a client asks SUSI AI to tell the value of a bitcoin, then the skill takes US dollars as the default currency. Thanks.

**Comment by hpdang** [comment]
very good, thank you @Manveer695. Please create another issue to tackle those currencies that you did not cover in this skill (like SGD, VND etc.). We don't have to cover all currencies right now but why not create a smart answer for the uncovered ones, can you try?

**Comment by hpdang** [comment]
@Orbiter there is already a bitcoin skill https://github.com/fossasia/susi_skill_data/blob/master/models/general/knowledge/en/bitcoin.txt

should we have two separate files: bitcoin.txt and currency_to_bitcoin.txt or combine them?

**Comment by Manveer695** [comment]
@hpdang Yes, sure ma'am. I am working on it and will send a PR soon. Thank you.

**Pull request merged**
