### PR TITLE
Update Poem.txt with more questions

### PR DESCRIPTION
**Pull request by dynamitechetan**
partially Fixes issue #119

### CODE REVIEW

**Review by DravitLochan — COMMENTED** [review]
How do you handle queries like tell me a poem, poetry please etc. these have no parameter from user. Will it not affect the API as "$1$" will be appended?

**Comment by dynamitechetan** [comment]
@DravitLochan  updated the skill.

**Review by DravitLochan — APPROVED** [review]
LGTM!

**Review by AliAyub007 — APPROVED** [review]
Good one 👍

**Review by saurabhjn76 — APPROVED** [review]

**Pull request merged**
