### PR TITLE
Added Atomic Number Skill

### PR DESCRIPTION
**Pull request by dynamitechetan**
Fixes **issue** #141 
**Etherpad Link**: http://dream.susi.ai/p/element
Screenshots for the change: 
image

### CODE REVIEW

**Review by Manveer695 — APPROVED** [review]
good one.

**Comment by hpdang** [comment]
@dynamitechetan please pay attention to the milestone and make sure to take care of those issues of the current milestone first, for instance #88

**Review by saurabhjn76 — APPROVED** [review]

**Review by hpdang — CHANGES_REQUESTED** [review]
@dynamitechetan there is a skill https://github.com/fossasia/susi_skill_data/blob/master/models/general/knowledge/en/atomic_mass.txt

please combine the two and rename to atomic. Thanks

**Comment by dynamitechetan** [comment]
okay.

**Comment by dynamitechetan** [comment]
@hpdang  please review.

**Pull request merged**
