### PR TITLE
Added examples to all skills in knowledge

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #192 (Partly)

**Changes:**
* Added examples for all skills in knowledge

@jyoth1raditya  @rishiraj824 @DravitLochan @saurabhjn76  Please review

### CODE REVIEW

**Review by madhavrathi — APPROVED** [review]

**Review by rishiraj824 — APPROVED** [review]

**Review by DravitLochan — APPROVED** [review]

**Review by saurabhjn76 — APPROVED** [review]

**Review by Laughing-Boy — APPROVED** [review]

**Review by AliAyub007 — APPROVED** [review]

**Review by AliAyub007 — COMMENTED** [review]
There are still conflicts in this PR.

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by uday96** [comment]
@mariobehling Resolved conflicts. Please merge.

**Comment by uday96** [comment]
@hpdang @mariobehling Please merge this PR.

**Pull request merged**
