### PR TITLE
Added 3 questions game like Amazon Alexa

### PR DESCRIPTION
**Pull request by dynamitechetan**
Fixes issue #154 progress on #88
Changes: added skill to ask user 3 questions
**Etherpad** Link: http://dream.susi.ai/p/three_ques
Similar to : https://www.amazon.com/gp/product/B01NC2BLGA?ref=skillrw_dsk_game_gw_0
Screenshots for the change: 
image

### CODE REVIEW

**Comment by DravitLochan** [comment]
@dynamitechetan Etherpad link?

**Comment by dynamitechetan** [comment]
@dravitlochan updated the comment

**Comment by Laughing-Boy** [comment]
@dynamitechetan , what about the answers?

**Comment by dynamitechetan** [comment]
I can provide the answers too, but are they needed? Let the user think of the answers.

**Comment by dynamitechetan** [comment]
@jyoth1raditya @madhavrathi @isuruAb @saurabhjn76 please review

**Comment by DravitLochan** [comment]
@dynamitechetan Answers might be needed as well. It would be good to provide answers as well!

**Review by hpdang — APPROVED** [review]

**Comment by hpdang** [comment]
@dynamitechetan your friend needs to review

**Review by saurabhjn76 — APPROVED** [review]

**Review by hpdang — CHANGES_REQUESTED** [review]
can we move this to entertainment model, please?

**Review by madhavrathi — APPROVED** [review]
Please consider it moving to entertainment folder as asked       by @hpdang

**Comment by dynamitechetan** [comment]
@hpdang  please review. I updated the PR as per your comments.

**Review by Laughing-Boy — APPROVED** [review]

**Review by madhavrathi — APPROVED** [review]

**Pull request merged**
