### PR TITLE
wallpapers skills added

### LINKED ISSUE #58: wallpapers skill absent
**Actual Behaviour**
No skill to get wallpapers.

**Expected Behaviour**

SUSI clients should return wallpapers when asked for.

**Steps to reproduce it**
I will be adding 2 different skills. One will return random wallpapers and the other one will return wallpaper for a particular search item.

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.
Yes

### PR DESCRIPTION
**Pull request by DravitLochan**
Related to [#126](https://github.com/fossasia/susi_server/issues/126)
**Changes:**
Fixes #58 : 
 get random wallpapers skill file added
 get wallpapers for a particular search item

### CODE REVIEW

**Review by saurabhjn76 — APPROVED** [review]

**Review by Laughing-Boy — APPROVED** [review]

**Review by AliAyub007 — APPROVED** [review]

**Comment by mariobehling** [comment]
Which issue #126?

Please provide an etherpad dream to test it.

**Comment by DravitLochan** [comment]
[random wallpapers](dream.susi.ai/p/wallpapers)
[particular wallpaper](dream.susi.ai/p/wallpaper)

**Review by rishiraj824 — APPROVED** [review]

**Comment by hpdang** [comment]
very unlikely people will ask for this, let's focus on something, please focus the next week on image skill

**Comment by DravitLochan** [comment]
I am focusing on images only. No other priority for skills right now. But I'd like to share certain views about skills. Please correct me if I am wrong. 
1. I got the idea about wallpapers from my younger brother. He told me that his pals are using Google Allo 
    to find cool wallpapers. Missing on the skills, we might decrease hit ratio and go on filling this 
    [list](api.susi.ai/susi/unanswered.txt).
2. In near future, We are going to experience a world of bots only(Let's just stick to chat bots for now), 
    Getting a miss on Susi and a hit on some other bot.. It might led to shift of user base.

**Pull request closed without merging**
