### PR TITLE
Fixes #86:Added skill for converting binary into decimal

### LINKED ISSUE #86: No skill for converting a binary number added by user into decimal
**Actual Behaviour**

No skill for converting a binary number added by user into decimal

**Expected Behaviour**

There should be a skill like this.

**Would you like to work on the issue?**

Yes, sending PR

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #86 

Changes:Added skill for converting binary into decimal

Screenshots for the change: 
hy

### CODE REVIEW

**Review by Laughing-Boy — APPROVED** [review]

**Comment by AliAyub007** [comment]
@madhavrathi Kindly give etherpad link also.

**Review by AliAyub007 — APPROVED** [review]

**Review by saurabhjn76 — APPROVED** [review]
:+1:

**Comment by hpdang** [comment]
guys, let focus on something that a user who would more likely ask or something that useful for us. Conversion could be a good topic. @madhavrathi perhaps, check how many conversion related skills are there and improve them (make sure when user ask to convert something, susi is able to give an answers: currency, unit, temperature etc. Please make **Conversion** as your focus of Milestone 6

**Comment by madhavrathi** [comment]
@hpdang I will make sure that i am able to improve conversion based skills.
Thanks

**Pull request closed without merging**
