### PR TITLE
Correct reponses to user statements

### PR DESCRIPTION
**Pull request by Laughing-Boy**
Fixes issue #117 
image

### CODE REVIEW

**Review by hpdang — CHANGES_REQUESTED** [review]
good start but we are expecting a bit more, please think of other statements that user might say and I don't this skill belongs to knowledge model.

**Review by hpdang — CHANGES_REQUESTED** [review]
I don't think this skill belongs to knowledge, perhaps smalltalk

**Comment by hpdang** [comment]
@jyoth1raditya I am thinking if we should label the skill: user_positive_expression instead of ('good'), then here we define all the positive statements of users (I agree, I totally agree, I am fine, I am good, I am pretty, I am full etc.) like what you did, then we can continue to extend. Take out the negative sentences (i don't know, did not, ..+not). After that we can create another issue/pr for a skill: user_negative_expression

**Comment by Laughing-Boy** [comment]
@hpdang , Incorporated your suggestions 👍

**Comment by hpdang** [comment]
great, thank you @jyoth1raditya

**Pull request merged**
