### PR TITLE
Implemented hex to decimal and viceversa.

### PR DESCRIPTION
**Pull request by Laughing-Boy**
Fixes issue #162, Susi responds to queries correctly.

Screenshots for the change: 
image

Etherpad link : http://dream.susi.ai/p/hex_to_decimal

### CODE REVIEW

**Comment by Laughing-Boy** [comment]
@dynamitechetan @saurabh1295 @dravitlochan @isuruAb @uday96, Please review

**Review by uday96 — CHANGES_REQUESTED** [review]
Does it handle negative numbers too?

**Comment by Laughing-Boy** [comment]
@uday96, Yup It converts -ve numbers
image

**Review by uday96 — APPROVED** [review]
Cool :+1: 
@jyoth1raditya Dint see the etherpad link initially, Sorry :smile:

**Review by saurabhjn76 — APPROVED** [review]

**Review by DravitLochan — APPROVED** [review]

**Review by chashmeetsingh — COMMENTED** [review]
Can we add, what's the hex for * and can you tell me the hex for *? And vice versa.

**Review by madhavrathi — APPROVED** [review]

**Review by mariobehling — CHANGES_REQUESTED** [review]
Provide more questions/ways users could ask for this.

**Review by isuruAb — COMMENTED** [review]
add more questions. 👍

**Review by hpdang — CHANGES_REQUESTED** [review]
@jyoth1raditya please combine this with assisting skill, change the skill name to decimal (store all the decimal conversation) https://github.com/fossasia/susi_skill_data/blob/master/models/general/problemsolving/en/decimalToBinary.txt

**Comment by Laughing-Boy** [comment]
@hpdang I have done the changes. Thanks for assistance :+1:.

**Comment by Laughing-Boy** [comment]
@hpdang, I added more questions. This PR is ready to merge.

**Pull request merged**
