### PR TITLE
Related #126 When is and days left in specific event skill added

### PR DESCRIPTION
**Pull request by AliAyub007**
Fixes issue #47  2 skills added to knowledge which tells us about when is any specific event and how many days left till any specific event.

### CODE REVIEW

**Review by dynamitechetan — APPROVED** [review]

**Review by chashmeetsingh — APPROVED** [review]

**Review by Laughing-Boy — APPROVED** [review]

**Comment by mariobehling** [comment]
Which issue? Where? Link? Issues should be opened in this specific project tracker.

Please provide an Etherpad dream to test this skill.

Follow best practices in all projects!

Please do follow best practices. Read again the guidelines to understand the best practices of FOSSASIA.

**Comment by AliAyub007** [comment]
Issue #47  
Etherpad link: http://dream.susi.ai/p/whenis

**Comment by hpdang** [comment]
@AliAyub007 Susi is already able to answer these questions when I tested (without your skill). Maybe this skill was written and stored elsewhere. Can you please find out? 

Regarding 'when is' question, susi does have some fixed answers for **smalltalk** like "when is your birthday, when is my birthday, when is my mother's birthday, when is my wedding etc." we can perhaps create some smart/funny answer those

**Comment by AliAyub007** [comment]
@hpdang  I have checked it now and even before making skill i didn't get the reply from susi. I tested it again here is the result. Currently there is no when is skill in susi_skill_data repository i searched for it.

whenis

**Pull request merged**
