### PR TITLE
Added Relevant Query for the example

### PR DESCRIPTION
**Pull request by sachincool**
Fixes https://github.com/fossasia/susi_skill_data/issues/300

### CODE REVIEW

**Review by the-codingninja — APPROVED** [review]
LGTM!!

**Comment by mariobehling** [comment]
Thanks, but for such small changes, please use https://skills.susi.ai

**Comment by sachincool** [comment]
@mariobehling  thanks, i sent the commit and it got accepted right away. i had a small query :-  Can  anyone edit any skill in the skill db  using the site with just a login ? or does someone review the commits too ?

**Comment by saurabhjn76** [comment]
@sachincool Currently, to create/edit skills one just needs a login https://skills.susi.ai

**Pull request closed without merging**
