### PR TITLE
Fixes #126: Susi now gives response to 'who are you'

### LINKED ISSUE #126: Susi is giving a non-human answer to the question 'What is your name'
**Actual Behaviour**

Once user types what is your name? 
Susi answers: your name is a 2017 Japanese movie by Shinkai Makoto. 
This answer is correct but user wants to know if susi can tell her name 

**Expected Behaviour**
- My name is Susi.  

**Steps to reproduce it**
- find out where susi get the answer for that question and fix it

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #126 

Changes: Susi now responds properly to queries like who are you 

Link to dream : http://dream.susi.ai/p/introduction

### CODE REVIEW

**Comment by hpdang** [comment]
@madhavrathi did you find out what susi give the answer 'your name is a 2017 Japanese movie by Shinkai Makoto' and where is that skill stored? please do so

**Comment by madhavrathi** [comment]
@hpdang Yes, i am finding that skill for some time. Will post it here asap.
Thanks

**Review by dynamitechetan — APPROVED** [review]

**Comment by madhavrathi** [comment]
@hpdang @dynamitechetan I have searched every skill in models folder, but no skill is having query like "what is *".
Can you suggest me what should i do here.
Thanks

**Comment by hpdang** [comment]
@madhavrathi please change the file name to aboutsusi and add this skill into smalltalk model. We will use this skill for all questions about susi (name, age, abilities etc.). Thanks

**Review by hpdang — CHANGES_REQUESTED** [review]
please see my last comment

**Comment by madhavrathi** [comment]
@hpdang Made the suggested changes, please review.
Thanks

**Pull request merged**
