### PR TITLE
Removed space and updated images to avoid copyright issues

### PR DESCRIPTION
**Pull request by AliAyub007**
Fixes issue #270 

Changes: 
Removed spaces as skills were not working with space after !example: and updated images from a source that doesn't need attribution for commercial use.

### CODE REVIEW

**Comment by AliAyub007** [comment]
@saurabhjn76 @dynamitechetan @betterclever kindly review this PR.

**Review by betterclever — APPROVED** [review]

**Review by mariobehling — CHANGES_REQUESTED** [review]
All images need to be square.

**Review by dynamitechetan — APPROVED** [review]

**Comment by dynamitechetan** [comment]
Yes please change images to sqaure and larger than 200x200. Rest seems fine to me.

**Comment by AliAyub007** [comment]
I will make them square 👍

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
