### PR TITLE
skill images: to give user an image response when asked

### PR DESCRIPTION
**Pull request by DravitLochan**
Fixes issue #123 

Changes: added skill.txt in entertainment folder.
Screenshots for the change: 
image
image
image
image
image
image

### CODE REVIEW

**Review by madhavrathi — APPROVED** [review]

**Comment by mariobehling** [comment]
@DravitLochan Please always add an Etherpad where reviewers can try out a new skill. Where is your testpad?

**Comment by DravitLochan** [comment]
Won't happen from next time. Please test the skill. Etherpad link -> http://dream.susi.ai/p/images

**Comment by mariobehling** [comment]
@DravitLochan Please add many more sentences to request an image. People use all kinds of different words and sentence structures.

**Comment by mayank408** [comment]
@mariobehling If this skill is added, should I open an issue in different clients to show image action type?

**Comment by mariobehling** [comment]
@mayank408 You can open an issue already in other clients now. @hpdang will review skills in more detail, but she is traveling to Taipei at the moment. So, we need to be patient a bit. LGTM!

**Comment by DravitLochan** [comment]
@mariobehling sure thing. Till then I'll utilise this time to add more questions :)

**Comment by DravitLochan** [comment]
@dynamitechetan @saurabhjn76 @jyoth1raditya @chashmeetsingh @heychirag Please review!

**Review by Laughing-Boy — APPROVED** [review]
Awesome 👍

**Review by madhavrathi — APPROVED** [review]

**Review by saurabhjn76 — APPROVED** [review]

**Review by dynamitechetan — APPROVED** [review]

**Pull request merged**
